# Generated by the copilot 
# List to store appointments
appointments = []

def book_appointment(patient_name, practitioner_name, appointment_time):
    """Store a new appointment."""

    appointment = {
        "patient_name": patient_name,
        "practitioner_name": practitioner_name,
        "appointment_time": appointment_time
    }

    appointments.append(appointment)

    print("Appointment booked successfully.")

# Example usage
book_appointment("John Doe", "Dr. Smith", "10:00 AM")
book_appointment("Jane Doe", "Dr. Brown", "11:00 AM")

# Display all appointments
print("\nAppointments:")
for appointment in appointments:
    print(appointment)